main:
  - name: Projects
    url: projects/
    weight: 10

  - name: Papers
    url: /#papers
    weight: 20

  - name: Team
    url: teams/
    weight: 30

  - name: Courses
    url: courses/
    weight: 40
  
    # Mother1
  - name: Events
    weight: 50
    hasChildren: true

  # Child
  - parent: Events
    name: Talks
    url: /#talks

  # Child
  - parent: Events
    name: News
    url: /#news

   # Mother2
  - name: Learn About Us
    weight: 60
    hasChildren: true

  # Child
  - parent: Learn About Us
    name: Experience
    url: experience/
  
  # Child
  - parent: Learn About Us
    name: Facility
    url: facilities/