main:
  - name: Projects
    url: projects/
    weight: 10

  - name: Papers
    url: /#papers
    weight: 11

  # 顶层下拉菜单：Events
  - name: Events
    url: "#"
    weight: 12

  # 子菜单：Talks
  - name: Talks
    url: /#talks
    parent: Events
    weight: 121

  # 子菜单：News
  - name: News
    url: /#news
    parent: Events
    weight: 122

  - name: Experience
    url: experience/
    weight: 20

  - name: Team
    url: teams/
    weight: 30

  - name: Courses
    url: courses/
    weight: 40
