main:
  - name: Projects
    url: projects/
    weight: 10

  - name: Papers
    url: /#papers
    weight: 20

  # Mother
  - name: Events
    weight: 30
    hasChildren: true

  # Child
  - parent: Events
    name: Talks
    url: /#talks

  # Child
  - parent: Events
    name: News
    url: /#news

  - name: Experience
    url: experience/
    weight: 40

  - name: Team
    url: teams/
    weight: 50

  - name: Courses
    url: courses/
    weight: 60